version: "3"

services:

  traefik:
    image: traefik:v1.7
    container_name: traefik
    command: "--api --docker --logLevel=DEBUG"
    ports:
      - "8080:8080"
      - "8088:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
